apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content-v1
data:
  index.html: |
   <html>
     <head>
      <title>NGINX</title>
     </head>
    <body>
    <p>frontend v1</p>
    </body>
   </html>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content-v2
data:
  index.html: |
   <html>
     <head>
      <title>NGINX</title>
     </head>
    <body>
    <p>frontend v2</p>
    </body>
   </html>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  1024;
    }
    http {
      access_log	/var/log/nginx/access.log;
      server {
        server_name   nginx;
        listen        80;
        location      / {
            root      /www;
            index     index.html;
        }
      }
    }
